name: clang-format-check

on:
  pull_request:
    branches: ['master']

jobs:
  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: '.'
            exclude: 'espert-core'
        
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format for C/C++ 
      uses: jidicula/clang-format-action@v4.11.0
      with:
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        clang-format-version: '17'
