name: clang-format-check

on: [push]

jobs:
  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        exclude: './espert-core'
        extensions: 'h,hh,c,cc,cpp'
        clangFormatVersion: 14
